Review PR
dezuz/Homework-4 pull request #1
Opened 2019-03-04 20:44 UTC by dezuz

2019-03-05 12:28 UTC, Taniann requested changes
read comments

2019-03-05 12:28 UTC, Taniann commented on .gitignore
> +
for future: that filemustn`'t be in your homework PR

2019-03-05 12:28 UTC, Taniann commented on src/com/mateacademy/collections/MyArrayList.java
> +        if (index > this.size ) {
better dont write this when it isnt required. 
what if index < 0

2019-03-05 12:28 UTC, Taniann commented on src/com/mateacademy/collections/MyArrayList.java
> +        if (index > this.size ) {
index also can be < 0

2019-03-05 19:34 UTC, Taniann approved these changes
good

2019-03-05 19:34 UTC, Taniann commented on src/com/mateacademy/collections/MyArrayList.java
> +            System.out.println("Please write a valid index");
better throw exception here with needed message

2019-03-24 14:42 UTC, Anderwerty requested changes

2019-03-24 14:42 UTC, Anderwerty commented on .gitignore
> +target/
Add a blank line at the end of the file.

2019-03-24 14:42 UTC, Anderwerty commented on pom.xml
> +        <!-- https://mvnrepository.com/artifact/junit/junit -->
Redundant comment. Remove it.

2019-03-24 14:42 UTC, Anderwerty commented on pom.xml
> +</project>
Add blank line a the end of the file.

2019-03-24 14:42 UTC, Anderwerty commented on src/main/java/com/mateacademy/collections/MyArrayList.java
> +        else {
You could remove else {

2019-03-24 14:42 UTC, Anderwerty commented on src/main/java/com/mateacademy/collections/MyArrayList.java
> +        }
remove }

2019-03-24 14:42 UTC, Anderwerty commented on src/main/java/com/mateacademy/collections/MyArrayList.java
> +            System.arraycopy(elements, index, elements, index - 1,
Why not in one line.

2019-03-24 14:42 UTC, Anderwerty commented on src/main/java/com/mateacademy/collections/MyArrayList.java
> +public class  MyArrayList <T> implements MyList<T>, Cloneable{
Please add @Override annotation for all override methods.

2019-03-24 14:42 UTC, Anderwerty commented on src/main/java/com/mateacademy/collections/MyLinkedList.java
> +public class MyLinkedList<T> implements MyList<T> {
Add override annotation where it should be.

2019-03-24 14:42 UTC, Anderwerty commented on src/test/java/com/mateacademy/collections/MyArrayListTest.java
> +}
Add  a blank line at the end of the file.

2019-03-24 14:42 UTC, Anderwerty commented on src/test/java/com/mateacademy/collections/MyArrayListTest.java
> +public class MyArrayListTest {
You should add tests for all public methods.

2019-03-24 14:42 UTC, Anderwerty commented on src/test/java/com/mateacademy/collections/MyLinkedListTest.java
> +public class MyLinkedListTest {
You should add tests for all public methods.

2019-03-24 14:42 UTC, Anderwerty commented on src/test/java/com/mateacademy/collections/MyLinkedListTest.java
> +}
Add a blank line at the end of the file.

2019-03-24 14:42 UTC, Anderwerty commented on src/test/java/com/mateacademy/collections/MyStackTest.java
> +}
A blank line should be added.

2019-03-24 19:10 UTC, Anderwerty requested changes

2019-03-24 19:10 UTC, Anderwerty commented on src/main/java/com/mateacademy/collections/MyArrayList.java
> +            throw new ArrayIndexOutOfBoundsException("Index: " + index + ", Size: " + size);
You should have 3 tests for this method.

2019-03-24 19:10 UTC, Anderwerty commented on src/main/java/com/mateacademy/collections/MyList.java
> +public interface MyList<T> {
Please format this code.

2019-03-24 19:10 UTC, Anderwerty commented on src/test/java/com/mateacademy/collections/MyStackTest.java
> +    @Test(expected = ArrayIndexOutOfBoundsException.class)
Please also check exception message

2019-03-24 19:10 UTC, Anderwerty commented on src/test/java/com/mateacademy/collections/MyLinkedListTest.java
> +    public void testRemoveMethodToException() {
Please also check exception message

2019-03-24 19:10 UTC, Anderwerty commented on src/test/java/com/mateacademy/collections/MyLinkedListTest.java
> +    public void testGetMethodToException() {
Please also check exception message

2019-03-24 19:10 UTC, Anderwerty commented on src/test/java/com/mateacademy/collections/MyArrayListTest.java
> +    public void testRemoveMethodToExceptions() {
Please also check exception message

2019-03-24 20:45 UTC, Anderwerty approved these changes

2019-03-25 19:10 UTC, merged